name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build with Next.js
        run: pnpm run build
        
      - name: Ensure app-ads.txt is preserved
        run: |
          # 모든 .txt 파일 제거 (app-ads.txt와 ads.txt 제외)
          find dist -name "*.txt" -type f ! -name "app-ads.txt" ! -name "ads.txt" -delete
          # public 폴더의 txt 파일들을 dist로 직접 복사 (덮어쓰기)
          cp -f public/app-ads.txt dist/app-ads.txt
          cp -f public/ads.txt dist/ads.txt
          echo "app-ads.txt and ads.txt preserved successfully"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4